# Tipo de banco
quarkus.datasource.db-kind=postgresql

# Usuário e senha do seu PostgreSQL
quarkus.datasource.username=postgres
quarkus.datasource.password=1234

# URL de conexão (ajuste conforme seu banco local)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/api.bancaria

# Geração automática das tabelas
quarkus.hibernate-orm.database.generation=update
